"""Obsidian vault bridge.

Each repo becomes one `.md` file under `<vault_path>/<subdir>/`. The
file opens with a YAML frontmatter block that Obsidian renders as
"Properties" (list for tags, nested block for upstream metadata) and
is also Dataview-queryable. The body contains operator notes in
chronological order.

Two directions are supported:

- **export** (added in 2.3.0): DB -> markdown. Rewrites every file
  atomically, no body preservation needed - the DB is the source of
  truth and notes are rendered from there.

- **sync** (added in 2.5.0): operator-curated markdown frontmatter
  edits flow back into the DB. Only a fixed, partitioned set of
  fields is read: `status` and `tags`. DB-authoritative fields
  (`upstream.*`, `last_touched`, `remote_url`, `path`, `added`,
  `nostos_id`) are ignored on read and regenerated on the
  subsequent write. Body content (notes) stays DB-authoritative;
  use `nostos note` to add new notes. This partitioning removes
  the need for conflict resolution: the two sides never write to
  the same field.

Design choices
- YAML frontmatter is generated by a tight, deterministic writer and
  parsed by an equally tight reader that only understands the shapes
  we produce. No runtime dependency on a general YAML library.
- Files are rewritten in place on every sync / export. A crash mid-
  write leaves the vault untouched thanks to the temp-file + rename
  atomic-write pattern.
- The index DB is the authoritative store. Vault files are a
  reconciliable projection of it.

Security
- Vault files are written 0600 on Unix (same posture as the index DB).
- The target directory is created 0700 if missing.
- Credentials in `remote_url` are defensively redacted on render.
"""

from __future__ import annotations

import datetime
import glob
import os
import re
import stat
import sys
from typing import Any

__all__ = [
    "VaultTarget",
    "export_repo",
    "export_all",
    "parse_frontmatter",
    "repo_slug",
    "render_markdown",
    "sync_vault",
]


class VaultTarget:
    """Resolved destination directory for vault exports."""

    def __init__(self, vault_path: str, subdir: str = "repos") -> None:
        self.root = os.path.abspath(os.path.expanduser(vault_path))
        self.subdir = subdir
        self.repos_dir = os.path.join(self.root, subdir)

    def ensure(self) -> None:
        os.makedirs(self.repos_dir, exist_ok=True)
        if sys.platform != "win32":
            try:
                os.chmod(self.repos_dir, 0o700)
            except OSError:
                pass


# ---------- slugs ----------

_SLUG_RE = re.compile(r"[^a-z0-9._-]+")


def repo_slug(repo: dict[str, Any], upstream: dict[str, Any] | None) -> str:
    """Build a stable filename slug for a repo.

    Preference: "<owner>-<name>" from upstream metadata if available;
    otherwise the last path segment of the local clone. The slug is
    lowercased and has all non-portable characters replaced with '-'.
    """
    if upstream and upstream.get("owner") and upstream.get("name"):
        base = f"{upstream['owner']}-{upstream['name']}"
    else:
        base = os.path.basename(repo["path"].rstrip(os.sep))
    base = base.lower().replace("/", "-")
    base = _SLUG_RE.sub("-", base).strip("-") or "repo"
    return base


# ---------- YAML frontmatter writer ----------


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    text = str(value)
    # Always double-quote strings to avoid YAML ambiguity (dates,
    # booleans-that-are-actually-strings, leading hash, etc.)
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _yaml_list_scalar(value: Any) -> str:
    return _yaml_scalar(value)


def _render_frontmatter(data: dict[str, Any]) -> str:
    """Emit YAML for a small, known set of shapes:

    - top-level scalars (str, int, bool, None)
    - a `tags` key with a flat list of strings
    - a nested `upstream` key whose value is a flat dict of scalars
    """
    lines: list[str] = ["---"]
    for key, value in data.items():
        if key == "tags":
            if not value:
                lines.append("tags: []")
            else:
                items = ", ".join(_yaml_list_scalar(t) for t in value)
                lines.append(f"tags: [{items}]")
        elif isinstance(value, dict):
            lines.append(f"{key}:")
            for sub_key, sub_val in value.items():
                lines.append(f"  {sub_key}: {_yaml_scalar(sub_val)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return "\n".join(lines)


# ---------- redaction ----------


_CRED_URL_RE = re.compile(r"(https?://)([^@/\s]+)@")


def _redact_remote_url(url: str | None) -> str | None:
    if not url:
        return url
    return _CRED_URL_RE.sub(r"\1***@", url)


# ---------- markdown rendering ----------


def render_markdown(
    repo: dict[str, Any],
    upstream: dict[str, Any] | None,
    notes: list[dict[str, Any]],
    *,
    nostos_version: str = "unknown",
) -> str:
    """Produce the full markdown content for one repo."""
    frontmatter: dict[str, Any] = {
        "nostos_id": repo["id"],
        "path": repo["path"],
        "remote_url": _redact_remote_url(repo.get("remote_url")),
        "source": repo.get("source"),
        "status": repo["status"],
        "quiet": bool(repo.get("quiet")),
        "added": repo.get("added_at"),
        "last_touched": repo.get("last_touched_at"),
        "tags": list(repo.get("tags", [])),
    }

    if upstream:
        frontmatter["upstream"] = {
            "provider": upstream.get("provider"),
            "host": upstream.get("host"),
            "owner": upstream.get("owner"),
            "name": upstream.get("name"),
            "stars": upstream.get("stars"),
            "forks": upstream.get("forks"),
            "open_issues": upstream.get("open_issues"),
            "archived": bool(upstream.get("archived")),
            "default_branch": upstream.get("default_branch"),
            "license": upstream.get("license"),
            "last_push": upstream.get("last_push"),
            "latest_release": upstream.get("latest_release"),
            "fetched_at": upstream.get("fetched_at"),
        }

    header_repo = ""
    if upstream and upstream.get("owner") and upstream.get("name"):
        header_repo = f"{upstream['owner']}/{upstream['name']}"
    else:
        header_repo = os.path.basename(repo["path"].rstrip(os.sep))

    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    body_lines: list[str] = [
        "",
        "",
        f"# {header_repo}",
        "",
        f"*Exported by nostos {nostos_version} on {now}*",
        "",
    ]

    if upstream and upstream.get("description"):
        body_lines.extend(["", "## Description", "", str(upstream["description"]), ""])

    if notes:
        body_lines.extend(["", "## Notes", ""])
        for n in notes:
            body_lines.append(f"- **{n['created_at']}** - {n['body']}")
        body_lines.append("")
    else:
        body_lines.extend(["", "## Notes", "", "_No notes yet._", ""])

    return _render_frontmatter(frontmatter) + "\n".join(body_lines)


# ---------- write ----------


def _chmod_0600(path: str) -> None:
    if sys.platform == "win32":
        return
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def export_repo(
    target: VaultTarget,
    repo: dict[str, Any],
    upstream: dict[str, Any] | None,
    notes: list[dict[str, Any]],
    *,
    nostos_version: str = "unknown",
) -> str:
    """Write one repo's markdown to the vault. Returns the file path."""
    target.ensure()
    slug = repo_slug(repo, upstream)
    out_path = os.path.join(target.repos_dir, slug + ".md")
    md = render_markdown(
        repo, upstream, notes, nostos_version=nostos_version
    )
    # Atomic write: temp file + rename so a crash mid-write does not
    # leave a partial file in the vault.
    tmp_path = out_path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(md)
    _chmod_0600(tmp_path)
    os.replace(tmp_path, out_path)
    return out_path


def export_all(
    target: VaultTarget,
    loader: Any,
    *,
    nostos_version: str = "unknown",
) -> list[str]:
    """Export every repo in the index to the vault.

    `loader` must expose .iter_repos() -> list of dicts with keys
    matching index.get_repo output plus optional 'upstream' and 'notes'.
    Kept decoupled from core.index so tests can feed synthetic data.
    """
    written: list[str] = []
    for repo in loader.iter_repos():
        upstream = repo.get("upstream")
        notes = repo.get("notes", [])
        path = export_repo(
            target, repo, upstream, notes, nostos_version=nostos_version
        )
        written.append(path)
    return written


# ---------- frontmatter parser (narrow, vault-shape only) ----------


_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*(?:\n|$)", re.DOTALL)


class FrontmatterError(ValueError):
    """Raised when a vault file's frontmatter cannot be parsed."""


def _unquote(value: str) -> str:
    """Strip a leading+trailing quote pair if present, handling escapes.

    Only understands the exact quoted-string shape our writer emits:
    double quotes with \\\\ and \\" escapes.
    """
    value = value.strip()
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        inner = value[1:-1]
        return inner.replace('\\"', '"').replace("\\\\", "\\")
    return value


def _parse_scalar(raw: str) -> Any:
    raw = raw.strip()
    if raw == "null" or raw == "~" or raw == "":
        return None
    if raw == "true":
        return True
    if raw == "false":
        return False
    # Integer scalar (no leading zero)
    if raw.lstrip("-").isdigit():
        return int(raw)
    return _unquote(raw)


def _parse_flow_list(raw: str) -> list[str]:
    """Parse `[a, b, c]` or `["a", "b"]` into a list of strings."""
    inner = raw.strip()
    if not (inner.startswith("[") and inner.endswith("]")):
        raise FrontmatterError(f"expected flow list, got {raw!r}")
    inner = inner[1:-1].strip()
    if not inner:
        return []
    # Split on commas outside of quotes. Our writer never nests lists
    # or emits commas inside tag values, so a naive state machine is
    # sufficient.
    items: list[str] = []
    current: list[str] = []
    in_quote = False
    escape = False
    for ch in inner:
        if escape:
            current.append(ch)
            escape = False
            continue
        if ch == "\\" and in_quote:
            current.append(ch)
            escape = True
            continue
        if ch == '"':
            current.append(ch)
            in_quote = not in_quote
            continue
        if ch == "," and not in_quote:
            items.append("".join(current).strip())
            current = []
            continue
        current.append(ch)
    last = "".join(current).strip()
    if last:
        items.append(last)
    return [_unquote(item) for item in items]


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Extract the YAML frontmatter and body from a vault markdown file.

    Returns (frontmatter_dict, body). Raises FrontmatterError if the
    `---` fence is absent or malformed. Only the shapes nostos
    itself writes are recognised:

    - top-level scalars (str / int / bool / null)
    - `tags: [...]` flow list OR `tags:\\n  - item\\n  - item` block list
    - one-level nested dict under `upstream:` (preserved but NOT
      mined; sync ignores it, the DB is authoritative here)
    """
    m = _FRONTMATTER_RE.match(text)
    if m is None:
        raise FrontmatterError("no frontmatter block found")
    yaml_block = m.group(1)
    body = text[m.end():]

    result: dict[str, Any] = {}
    lines = yaml_block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.rstrip()
        if not stripped or stripped.startswith("#"):
            i += 1
            continue

        # Top-level indent? Anything further indented belongs to a
        # nested block started by a previous line; the top-level walker
        # skips indented lines until the nested section is absorbed.
        if line.startswith(" ") or line.startswith("\t"):
            i += 1
            continue

        if ":" not in stripped:
            raise FrontmatterError(f"malformed frontmatter line: {stripped!r}")
        key, _, rest = stripped.partition(":")
        key = key.strip()
        rest = rest.strip()

        if key == "tags":
            if rest.startswith("["):
                result["tags"] = _parse_flow_list(rest)
                i += 1
                continue
            if rest == "":
                # Block-style list: subsequent indented "- item" lines
                tags: list[str] = []
                j = i + 1
                while j < len(lines):
                    sub = lines[j]
                    if sub.startswith(" ") or sub.startswith("\t"):
                        s = sub.strip()
                        if s.startswith("-"):
                            tags.append(_unquote(s[1:].strip()))
                        elif not s or s.startswith("#"):
                            pass
                        else:
                            break
                        j += 1
                        continue
                    break
                result["tags"] = tags
                i = j
                continue
            raise FrontmatterError(f"cannot parse tags value: {rest!r}")

        if rest == "":
            # Nested mapping (e.g. upstream:). Skip the nested block;
            # the DB owns those fields and sync does not reconcile them.
            j = i + 1
            while j < len(lines) and (
                lines[j].startswith(" ") or lines[j].startswith("\t") or not lines[j].strip()
            ):
                j += 1
            i = j
            continue

        result[key] = _parse_scalar(rest)
        i += 1

    return result, body


# ---------- sync ----------


_ALLOWED_SYNC_STATUSES: frozenset[str] = frozenset(
    {"new", "reviewed", "in-use", "dropped", "flagged"}
)

# ---------- note body parser ----------

_NOTE_BULLET_RE = re.compile(
    r"^-\s+\*\*(.+?)\*\*\s*[-:]\s*(.+)$"
)


def parse_notes_from_body(body: str) -> list[dict[str, str]]:
    """Extract notes from the markdown body's ## Notes section.

    Only bullets matching the exact pattern our writer emits are
    recognised: `- **<timestamp>** - <body>`. Everything else is
    silently ignored (it might be a user-added heading, freeform
    text, etc. - those are not nostos-managed notes).
    """
    in_notes_section = False
    notes: list[dict[str, str]] = []
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("## Notes"):
            in_notes_section = True
            continue
        if in_notes_section and stripped.startswith("## "):
            break  # next section started
        if in_notes_section:
            m = _NOTE_BULLET_RE.match(stripped)
            if m:
                notes.append({
                    "created_at": m.group(1).strip(),
                    "body": m.group(2).strip(),
                })
    return notes


def sync_vault(
    target: VaultTarget,
    reader: Any,
    writer: Any,
    *,
    nostos_version: str = "unknown",
) -> dict[str, Any]:
    """Reconcile the vault into the DB and re-render every vault file.

    Steps:
      1. Glob every `<repos_dir>/*.md`.
      2. Parse the frontmatter and pick off `nostos_id`, `status`,
         `tags`.
      3. If the repo still exists in the DB, call `writer.apply_edits`
         with the vault-side edits (status / tags replacement).
      4. Regenerate every `.md` in the repos_dir from the refreshed DB
         state so the file reflects the reconciled truth (upstream
         fields, timestamps, redaction).

    Orphaned vault files (whose `nostos_id` does not match any repo
    in the index) are left untouched and reported in `orphans` so the
    operator can decide whether to delete them or re-add the repo.

    `reader` and `writer` are adapters so this function is trivially
    unit-testable without a real SQLite index.
    """
    stats: dict[str, Any] = {
        "files_scanned": 0,
        "edits_applied": 0,
        "status_changed": 0,
        "tags_changed": 0,
        "notes_added": 0,
        "orphans": [],
        "parse_errors": [],
        "files_rewritten": 0,
    }

    if not os.path.isdir(target.repos_dir):
        return stats

    pattern = os.path.join(target.repos_dir, "*.md")
    for md_path in sorted(glob.glob(pattern)):
        stats["files_scanned"] += 1
        try:
            with open(md_path, encoding="utf-8") as f:
                text = f.read()
        except OSError as e:
            stats["parse_errors"].append({"path": md_path, "error": f"read: {e}"})
            continue

        try:
            front, body = parse_frontmatter(text)
        except FrontmatterError as e:
            stats["parse_errors"].append({"path": md_path, "error": str(e)})
            continue

        repo_id = front.get("nostos_id")
        if not isinstance(repo_id, int):
            stats["orphans"].append(md_path)
            continue

        new_status = front.get("status")
        if isinstance(new_status, str) and new_status not in _ALLOWED_SYNC_STATUSES:
            stats["parse_errors"].append(
                {
                    "path": md_path,
                    "error": f"invalid status {new_status!r}",
                }
            )
            new_status = None

        raw_tags = front.get("tags")
        new_tags: list[str] | None = None
        if isinstance(raw_tags, list):
            new_tags = [str(t).lower() for t in raw_tags if str(t).strip()]

        # Parse notes from the body section
        vault_notes = parse_notes_from_body(body)

        applied = writer.apply_edits(
            repo_id=repo_id,
            status=new_status if isinstance(new_status, str) else None,
            tags=new_tags,
            new_notes=vault_notes,
        )
        if applied is None:
            stats["orphans"].append(md_path)
            continue
        if applied.get("repo_missing"):
            stats["orphans"].append(md_path)
            continue

        if applied.get("status_changed"):
            stats["status_changed"] += 1
        if applied.get("tags_changed"):
            stats["tags_changed"] += 1
        notes_added = applied.get("notes_added", 0)
        stats["notes_added"] += notes_added
        if applied.get("status_changed") or applied.get("tags_changed") or notes_added:
            stats["edits_applied"] += 1

    # Phase 2 of sync: regenerate every .md from the now-reconciled DB.
    target.ensure()
    for repo in reader.iter_repos():
        upstream = repo.get("upstream")
        notes = repo.get("notes", [])
        export_repo(
            target, repo, upstream, notes, nostos_version=nostos_version
        )
        stats["files_rewritten"] += 1

    return stats
