"""Obsidian vault export (one-way: DB -> markdown).

Each repo becomes one `.md` file under `<vault_path>/<subdir>/`. The
file opens with a YAML frontmatter block that Obsidian renders as
"Properties" (list for tags, nested block for upstream metadata) and
is also Dataview-queryable. The body contains operator notes in
chronological order.

Design choices
- YAML frontmatter is generated by a tight, deterministic writer that
  only emits shapes we control. No external YAML parser is needed;
  the vault is only read back in a future (Phase 4) two-way sync.
- Files are rewritten in place on every export (idempotent, no body
  preservation needed for one-way mode). The operator's own notes
  live in the DB, which is the source of truth.
- The index DB is the authoritative store. The vault is a view. If
  the vault file is deleted / the vault path changes, no data is lost
  and re-exporting rebuilds it.

Security
- Vault files are written 0600 on Unix (same posture as the index DB).
- The target directory is created 0700 if missing.
- Credentials in `remote_url` are expected to already be stripped by
  the `core.updater.sanitize_log_output` invoked at ingest time, but
  we redact defensively here as well.
"""

from __future__ import annotations

import datetime
import os
import re
import stat
import sys
from typing import Any

__all__ = [
    "VaultTarget",
    "export_repo",
    "export_all",
    "repo_slug",
    "render_markdown",
]


class VaultTarget:
    """Resolved destination directory for vault exports."""

    def __init__(self, vault_path: str, subdir: str = "repos") -> None:
        self.root = os.path.abspath(os.path.expanduser(vault_path))
        self.subdir = subdir
        self.repos_dir = os.path.join(self.root, subdir)

    def ensure(self) -> None:
        os.makedirs(self.repos_dir, exist_ok=True)
        if sys.platform != "win32":
            try:
                os.chmod(self.repos_dir, 0o700)
            except OSError:
                pass


# ---------- slugs ----------

_SLUG_RE = re.compile(r"[^a-z0-9._-]+")


def repo_slug(repo: dict[str, Any], upstream: dict[str, Any] | None) -> str:
    """Build a stable filename slug for a repo.

    Preference: "<owner>-<name>" from upstream metadata if available;
    otherwise the last path segment of the local clone. The slug is
    lowercased and has all non-portable characters replaced with '-'.
    """
    if upstream and upstream.get("owner") and upstream.get("name"):
        base = f"{upstream['owner']}-{upstream['name']}"
    else:
        base = os.path.basename(repo["path"].rstrip(os.sep))
    base = base.lower().replace("/", "-")
    base = _SLUG_RE.sub("-", base).strip("-") or "repo"
    return base


# ---------- YAML frontmatter writer ----------


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    text = str(value)
    # Always double-quote strings to avoid YAML ambiguity (dates,
    # booleans-that-are-actually-strings, leading hash, etc.)
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _yaml_list_scalar(value: Any) -> str:
    return _yaml_scalar(value)


def _render_frontmatter(data: dict[str, Any]) -> str:
    """Emit YAML for a small, known set of shapes:

    - top-level scalars (str, int, bool, None)
    - a `tags` key with a flat list of strings
    - a nested `upstream` key whose value is a flat dict of scalars
    """
    lines: list[str] = ["---"]
    for key, value in data.items():
        if key == "tags":
            if not value:
                lines.append("tags: []")
            else:
                items = ", ".join(_yaml_list_scalar(t) for t in value)
                lines.append(f"tags: [{items}]")
        elif isinstance(value, dict):
            lines.append(f"{key}:")
            for sub_key, sub_val in value.items():
                lines.append(f"  {sub_key}: {_yaml_scalar(sub_val)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return "\n".join(lines)


# ---------- redaction ----------


_CRED_URL_RE = re.compile(r"(https?://)([^@/\s]+)@")


def _redact_remote_url(url: str | None) -> str | None:
    if not url:
        return url
    return _CRED_URL_RE.sub(r"\1***@", url)


# ---------- markdown rendering ----------


def render_markdown(
    repo: dict[str, Any],
    upstream: dict[str, Any] | None,
    notes: list[dict[str, Any]],
    *,
    gitpulse_version: str = "unknown",
) -> str:
    """Produce the full markdown content for one repo."""
    frontmatter: dict[str, Any] = {
        "gitpulse_id": repo["id"],
        "path": repo["path"],
        "remote_url": _redact_remote_url(repo.get("remote_url")),
        "source": repo.get("source"),
        "status": repo["status"],
        "quiet": bool(repo.get("quiet")),
        "added": repo.get("added_at"),
        "last_touched": repo.get("last_touched_at"),
        "tags": list(repo.get("tags", [])),
    }

    if upstream:
        frontmatter["upstream"] = {
            "provider": upstream.get("provider"),
            "host": upstream.get("host"),
            "owner": upstream.get("owner"),
            "name": upstream.get("name"),
            "stars": upstream.get("stars"),
            "forks": upstream.get("forks"),
            "open_issues": upstream.get("open_issues"),
            "archived": bool(upstream.get("archived")),
            "default_branch": upstream.get("default_branch"),
            "license": upstream.get("license"),
            "last_push": upstream.get("last_push"),
            "latest_release": upstream.get("latest_release"),
            "fetched_at": upstream.get("fetched_at"),
        }

    header_repo = ""
    if upstream and upstream.get("owner") and upstream.get("name"):
        header_repo = f"{upstream['owner']}/{upstream['name']}"
    else:
        header_repo = os.path.basename(repo["path"].rstrip(os.sep))

    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    body_lines: list[str] = [
        "",
        "",
        f"# {header_repo}",
        "",
        f"*Exported by gitpulse {gitpulse_version} on {now}*",
        "",
    ]

    if upstream and upstream.get("description"):
        body_lines.extend(["", "## Description", "", str(upstream["description"]), ""])

    if notes:
        body_lines.extend(["", "## Notes", ""])
        for n in notes:
            body_lines.append(f"- **{n['created_at']}** - {n['body']}")
        body_lines.append("")
    else:
        body_lines.extend(["", "## Notes", "", "_No notes yet._", ""])

    return _render_frontmatter(frontmatter) + "\n".join(body_lines)


# ---------- write ----------


def _chmod_0600(path: str) -> None:
    if sys.platform == "win32":
        return
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def export_repo(
    target: VaultTarget,
    repo: dict[str, Any],
    upstream: dict[str, Any] | None,
    notes: list[dict[str, Any]],
    *,
    gitpulse_version: str = "unknown",
) -> str:
    """Write one repo's markdown to the vault. Returns the file path."""
    target.ensure()
    slug = repo_slug(repo, upstream)
    out_path = os.path.join(target.repos_dir, slug + ".md")
    md = render_markdown(
        repo, upstream, notes, gitpulse_version=gitpulse_version
    )
    # Atomic write: temp file + rename so a crash mid-write does not
    # leave a partial file in the vault.
    tmp_path = out_path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(md)
    _chmod_0600(tmp_path)
    os.replace(tmp_path, out_path)
    return out_path


def export_all(
    target: VaultTarget,
    loader: Any,
    *,
    gitpulse_version: str = "unknown",
) -> list[str]:
    """Export every repo in the index to the vault.

    `loader` must expose .iter_repos() -> list of dicts with keys
    matching index.get_repo output plus optional 'upstream' and 'notes'.
    Kept decoupled from core.index so tests can feed synthetic data.
    """
    written: list[str] = []
    for repo in loader.iter_repos():
        upstream = repo.get("upstream")
        notes = repo.get("notes", [])
        path = export_repo(
            target, repo, upstream, notes, gitpulse_version=gitpulse_version
        )
        written.append(path)
    return written
